# Generated by Django 6.0.6 on 2026-07-02 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='trips.trip', verbose_name='Поездка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'user'), name='unique_application_per_trip_user')],
            },
        ),
    ]
