services:
  - type: web
    name: tripmate
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn tripmate_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.13.4"
