# Generated by Django 6.0.6 on 2026-07-02 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trips/', verbose_name='Изображение')),
                ('departure_city', models.CharField(max_length=100, verbose_name='Город отправления')),
                ('destination', models.CharField(max_length=100, verbose_name='Пункт назначения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('budget', models.PositiveIntegerField(default=0, help_text='0 — бесплатно', verbose_name='Бюджет, ₽')),
                ('max_participants', models.PositiveSmallIntegerField(default=4, verbose_name='Максимум участников')),
                ('category', models.CharField(choices=[('walk', 'Прогулка'), ('weekend', 'Поездка на выходные'), ('hike', 'Поход'), ('event', 'Мероприятие'), ('carpool', 'Попутка'), ('excursion', 'Экскурсия'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('transport', models.CharField(choices=[('walk', 'Пешком'), ('car', 'Автомобиль'), ('train', 'Поезд'), ('bus', 'Автобус'), ('suburban', 'Электричка'), ('plane', 'Самолёт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Транспорт')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к участникам')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('interests', models.ManyToManyField(blank=True, related_name='trips', to='accounts.interest', verbose_name='Интересы поездки')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_trips', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
                'ordering': ['-created_at'],
            },
        ),
    ]
