# Generated by Django 6.0.6 on 2026-07-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[('walk', 'Прогулка'), ('weekend', 'Поездка на выходные'), ('hike', 'Поход'), ('event', 'Мероприятие'), ('excursion', 'Экскурсия'), ('bike_ride', 'Велопрогулка'), ('camping', 'Кемпинг'), ('food_tour', 'Гастротур'), ('photo_tour', 'Фототур'), ('road_trip', 'Автопутешествие'), ('volunteering', 'Волонтёрство'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
